#!/bin/sh 

# PROVIDE: serenitynow
# REQUIRE: LOGIN
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf to enable serenitynow:
#
# serenitynow_enable="YES"
#
#

. /etc/rc.subr 
name="serenitynow" 
rcvar=serenitynow_enable

pidfile="/var/run/${name}.pid"

required_files="/usr/local/share/${name}.d/${name}.sqlite3" 

sig_stop="INT"

start_cmd="${name}_start"

stop_cmd="${name}_stop"

serenitynow_start() {
	. /root/.${name}.env
	daemon --close-fds --restart --user ${name} --supervisor-pidfile ${pidfile} --output-file /var/log/${name} \
	/usr/local/bin/${name}
	echo "Starting serenitynow..."
}

serenitynow_stop() {
	kill -s TERM $(cat ${pidfile})
	echo "serenitynow was stopped."
}

load_rc_config $name
run_rc_command "$1"
