#!/bin/sh 

# PROVIDE: serenitynow
# REQUIRE: LOGIN
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf to enable serenitynow:
#
# serenitynow_enable="YES"
#
#

. /etc/rc.subr 
name="serenitynow" 
rcvar=${name}_enable

pidfile="/var/run/${name}.pid"
serenitynow_env_file="/root/.${name}.env"

required_files="/usr/local/share/${name}.d/${name}.sqlite3 /usr/local/bin/${name} ${serenitynow_env_file}" 

sig_stop="TERM"

start_cmd="${name}_start"

stop_cmd="${name}_stop"

serenitynow_start() {
	daemon --close-fds --restart --user ${name} --supervisor-pidfile ${pidfile} --output-file /var/log/${name} \
	/usr/local/bin/${name}
	echo "Starting ${name}..."
}

serenitynow_stop() {
	kill -s TERM $(cat ${pidfile})
	echo "${name} was stopped."
}

load_rc_config $name
run_rc_command "$1"
